version: "3"

services:
  mysql:
    image: mysql:latest  
    container_name: mysql
    env_file:
        - .env
    ports:
        - "3306:3306"
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10  
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - mysql_data:/var/lib/mysql
    
      
  bizware:
    build:
        context: . 
        dockerfile: Dockerfile 
    container_name: bizware
    env_file:
        - .env
    ports:
        - "8080:8080" 
    depends_on:
      mysql:
        condition: service_healthy
      
volumes:
  mysql_data: